"""mtecmqtt constants."""

from __future__ import annotations

from typing import Final

GROUP: Final = "group"
LENGTH: Final = "length"
MQTT: Final = "mqtt"
NAME: Final = "name"
SCALE: Final = "scale"
TYPE: Final = "type"
UNIT: Final = "unit"
UTF8: Final = "utf-8"
VALUE: Final = "value"
WRITABLE: Final = "writable"


CFG_MODBUS_IP: Final = "MODBUS_IP"
CFG_MODBUS_PORT: Final = "MODBUS_PORT"
CFG_MODBUS_SLAVE: Final = "MODBUS_SLAVE"
CFG_MODBUS_TIMEOUT: Final = "MODBUS_TIMEOUT"
CFG_MODBUS_RETRIES: Final = "MODBUS_RETRIES"
CFG_MODBUS_FRAMER: Final = "MODBUS_FRAMER"
CFG_MQTT_DISABLE: Final = "MQTT_DISABLE"
CFG_MQTT_SERVER: Final = "MQTT_SERVER"
CFG_MQTT_PORT: Final = "MQTT_PORT"
CFG_MQTT_LOGIN: Final = "MQTT_LOGIN"
CFG_MQTT_PASSWORD: Final = "MQTT_PASSWORD"
CFG_MQTT_TOPIC: Final = "MQTT_TOPIC"
CFG_MQTT_FLOAT_FORMAT: Final = "MQTT_FLOAT_FORMAT"
CFG_REFRESH_NOW: Final = "REFRESH_NOW"
CFG_REFRESH_DAY: Final = "REFRESH_DAY"
CFG_REFRESH_TOTAL: Final = "REFRESH_TOTAL"
CFG_REFRESH_CONFIG: Final = "REFRESH_CONFIG"
CFG_HASS_ENABLE: Final = "HASS_ENABLE"
CFG_HASS_BASE_TOPIC: Final = "HASS_BASE_TOPIC"
CFG_HASS_BIRTH_GRACETIME: Final = "HASS_BIRTH_GRACETIME"
CFG_DEBUG: Final = "DEBUG"
