"""mtecmqtt constants."""

from __future__ import annotations

from typing import Final

UTF8: Final = "utf-8"

REG_DEVICE_CLASS: Final = "hass_device_class"
REG_GROUP: Final = "group"
REG_LENGTH: Final = "length"
REG_MQTT: Final = "mqtt"
REG_NAME: Final = "name"
REG_PAYLOAD_OFF: Final = "hass_payload_off"
REG_PAYLOAD_ON: Final = "hass_payload_on"
REG_SCALE: Final = "scale"
REG_STATE_CLASS: Final = "hass_state_class"
REG_TYPE: Final = "type"
REG_UNIT: Final = "unit"
REG_VALUE: Final = "value"
REG_VALUE_TEMPLATE: Final = "hass_value_template"
REG_WRITABLE: Final = "writable"

HA_COMMAND_TOPIC: Final = "command_topic"
HA_DEVICE: Final = "device"
HA_DEVICE_CLASS: Final = "device_class"
HA_IDENTIFIERS: Final = "identifiers"
HA_MANUFACTURER: Final = "manufacturer"
HA_MODEL: Final = "model"
HA_NAME: Final = "name"
HA_PAYLOAD_OFF: Final = "payload_off"
HA_PAYLOAD_ON: Final = "payload_on"
HA_PAYLOAD_PRESS: Final = "payload_press"
HA_STATE_CLASS: Final = "state_class"
HA_STATE_TOPIC: Final = "state_topic"
HA_UNIQUE_ID: Final = "unique_id"
HA_UNIT_OF_MEASUREMENT: Final = "unit_of_measurement"
HA_VALUE_TEMPLATE: Final = "value_template"
HA_VIA_DEVICE: Final = "via_device"

CFG_MODBUS_IP: Final = "MODBUS_IP"
CFG_MODBUS_PORT: Final = "MODBUS_PORT"
CFG_MODBUS_SLAVE: Final = "MODBUS_SLAVE"
CFG_MODBUS_TIMEOUT: Final = "MODBUS_TIMEOUT"
CFG_MODBUS_RETRIES: Final = "MODBUS_RETRIES"
CFG_MODBUS_FRAMER: Final = "MODBUS_FRAMER"
CFG_MQTT_DISABLE: Final = "MQTT_DISABLE"
CFG_MQTT_SERVER: Final = "MQTT_SERVER"
CFG_MQTT_PORT: Final = "MQTT_PORT"
CFG_MQTT_LOGIN: Final = "MQTT_LOGIN"
CFG_MQTT_PASSWORD: Final = "MQTT_PASSWORD"
CFG_MQTT_TOPIC: Final = "MQTT_TOPIC"
CFG_MQTT_FLOAT_FORMAT: Final = "MQTT_FLOAT_FORMAT"
CFG_REFRESH_NOW: Final = "REFRESH_NOW"
CFG_REFRESH_DAY: Final = "REFRESH_DAY"
CFG_REFRESH_TOTAL: Final = "REFRESH_TOTAL"
CFG_REFRESH_CONFIG: Final = "REFRESH_CONFIG"
CFG_HASS_ENABLE: Final = "HASS_ENABLE"
CFG_HASS_BASE_TOPIC: Final = "HASS_BASE_TOPIC"
CFG_HASS_BIRTH_GRACETIME: Final = "HASS_BIRTH_GRACETIME"
CFG_DEBUG: Final = "DEBUG"
